mixed-port: 10801

allow-lan: true

log-level: info # 日志等级 silent/error/warning/info/debug

sniffer:
  enable: true

#  find-process-mode has 3 values:always, strict, off
#  - always, 开启，强制匹配所有进程
#  - strict, 默认，由 mihomo 判断是否开启
#  - off, 不匹配进程，推荐在路由器上使用此模式
find-process-mode: strict

# rule 规则匹配
# global 全局代理 (需要在 GLOBAL 策略组选择代理/策略)
# direct 全局直连

mode: rule

dns:
  enable: true

proxies:
- name: hk03
  type: ss
  server: hk03.htrkeod.top
  port: 31652
  cipher: aes-128-gcm
  password: b319989e-3aeb-4b0f-8841-72959e3f2084
  udp: true
- name: hk06
  type: ss
  server: hk06.htrkeod.top
  port: 10877
  cipher: aes-128-gcm
  password: b319989e-3aeb-4b0f-8841-72959e3f2084
  udp: true
- name: sgp01
  type: ss
  server: sgp01.ilgi30vro.top
  port: 32515
  cipher: aes-128-gcm
  password: b319989e-3aeb-4b0f-8841-72959e3f2084
  udp: true


proxy-groups:
  - name: 第一层外网分流
    type: url-test
    proxies:
    - hk03
    - hk06
    - sgp01

rules:
  # - DOMAIN-KEYWORD,.,DIRECT
  - DOMAIN-SUFFIX,local,DIRECT
  - IP-CIDR,127.0.0.0/8,DIRECT
  - IP-CIDR,172.16.0.0/12,DIRECT
  - IP-CIDR,192.168.0.0/16,DIRECT
  - IP-CIDR,10.0.0.0/8,DIRECT
  - IP-CIDR,17.0.0.0/8,DIRECT
  - IP-CIDR,100.64.0.0/10,DIRECT
  - IP-CIDR,224.0.0.0/4,DIRECT
  - IP-CIDR6,fe80::/10,DIRECT
  - DOMAIN-SUFFIX,cn,DIRECT
  - DOMAIN-KEYWORD,-cn,DIRECT
  - DOMAIN-KEYWORD,baidu,DIRECT
  # - GEOIP,CN,DIRECT
  - MATCH,第一层外网分流